#! /usr/bin/env python
from ecn_common.token_handle import TokenHandle
from pylab import rand
import rospy

group_name = str(int(1000*rand()))

rospy.init_node('node_' + group_name)

token = TokenHandle(group_name)

while not rospy.is_shutdown():
    print(group_name + " doing its Python job")
    
    token.update();
    rospy.sleep(1)
