#! /usr/bin/env python
from ecn_common.token_handle import TokenHandle
from pylab import rand
import rospy
import sys


group_name = str(int(1000*rand()))
rospy.init_node('node_' + group_name)
kill = -1

if len(sys.argv) == 5:
    rospy.sleep(int(sys.argv[1]))
    kill = int(sys.argv[2])
    
side = ''
r = rand()
if r < 0.2:
    side = 'left'
elif r < .4:
    side = 'right'
    
token = TokenHandle(side, group_name)

t0 = rospy.Time.now().to_sec()

while not rospy.is_shutdown():
    print(group_name + " doing its Python job")
    
    if kill != -1 and rospy.Time.now().to_sec() - t0 > kill:
        sys.exit(0)
    
    token.update();
    rospy.sleep(1)
